# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
# ~/.config/lazygit/config.yml

git:
  # Limit hash length for <c-o> to create shorter references.
  truncateCopiedCommitHashesTo: 7

  theme:
    selectedLineBgColor:
      - black # reverse
